### ISSUE TITLE
Telnet access

### ISSUE THREAD

**Issue by hgshoggins** [BwanaFr/minitel-server#2]
Is there any simple way of accessing this server with a simple telnet client? If so, are there parameters that need to be used for the communication to properly work? I'm thinking of `stty` options but I'm not really sure.

**Comment by BwanaFr** [comment]
Hello,

Unfortunately this server handles only Minitel protocol.
If you plan to use a telnet client, this client must be able to emulate Minitel protocol.

**Comment by hgshoggins** [comment]
Thank you. I'm getting a Minitel in the next few days, planning to make it work through its line with the `SoftModem` app on Asterisk, but I was looking for a way to test the server's behavior before even having the machine at hand.

**Comment by BwanaFr** [comment]
You can try with some Minitel emulator.
I used Xtel on Linux (you can also test Hyperterminal on Windows), then connect to the server using 3614, 3615 or 3611 TCP port.

There is also a ready to use Docker image on Docker hub : https://hub.docker.com/r/mdonze/minitel-server

**Comment by hgshoggins** [comment]
Thanks! I actually struggled a lot to try to install Xtel on a Fedora system to discover that I could use it with an Ubuntu distribution from scratch. Will test this out!

**Comment by BwanaFr** [comment]
You're welcome :)
This software was made for demonstration of how Minitel worked (with the real modem).
There are plenty of improvements to be done!

**Comment by hgshoggins** [comment]
It's working perfectly, thanks!
Now I need to find a way to hook the 3615 ULLA chat to an IRC server.
